name: Build DLLs
# Builds DLLs for 32 and 64-bit Windows for all supportet PHP versions.
# Based on https://github.com/php/php-windows-builder

on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
  release:
    types: [published]

jobs:
  windows:
    strategy:
      matrix:
        php-version: ["7.2", "7.3", "7.4", "8.0", "8.1", "8.2", "8.3", "8.4", "8.5"]
        arch: [x64, x86]
        ts: [nts, ts]
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # php-windows-builder handles building, testing and artifact packaging/upload automatically
      - name: Build and test the extension
        uses: php/php-windows-builder/extension@v1
        with:
          php-version: ${{ matrix.php-version }}
          arch: ${{ matrix.arch }}
          ts: ${{ matrix.ts }}
          args: --enable-igbinary --enable-debug-pack
          run-tests: true
          test-runner-args: "--show-diff tests"

  # Upload *.zip files with prebuild Windows binaries needed by the PIE installer to the release
  release_pie:
    if: ${{ github.event_name == 'release' }}
    needs: windows
    runs-on: ubuntu-latest
    steps:
      - name: Upload artifacts to the release
        uses: php/php-windows-builder/release@v1
        with:
          release: ${{ github.event.release.tag_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

  # Create and upload the *.tgz file needed for PECL to the release
  release_pecl:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Create pecl upload file
        run: pecl package
      - name: Upload artifacts to the release
        uses: actions/upload-artifact@v7
        with:
          archive: false
          name: igbinary-${{github.ref_name}}.tgz
          path: igbinary-${{github.ref_name}}.tgz
